kind: Deployment
apiVersion: apps/v1
metadata:
   name: kishq-app
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: kishq-app
   template:
      metadata:
        labels:
          app: kishq-app
      spec:
       containers:
        - name: kishq-app
          image: iamsaikishore/kishq-app
          imagePullPolicy: Always
          ports:
          - containerPort: 80
