kind: Service                             
apiVersion: v1
metadata:
  name: kishq-app
  labels:
    app: kishq-app
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: kishq-app                   
  type: NodePort                   
